/*
 * This file has been generated by flow2code
 * See: https://flow.liwe.org
 */

import { ILRequest, ILResponse, ILError, ILiWE } from '../../liwe/types';
import { send_error, send_ok, typed_dict } from "../../liwe/utils";
import { locale_load } from '../../liwe/locale';

import { perms } from '../../liwe/auth';
import { LiWEResponse, sendParametersError, sendResponse } from '../../liwe/response';

import {
	// endpoints function
	delete_tag_admin_module_del, get_tag_admin_list, get_tag_list, get_tag_search, patch_tag_admin_fields,
	patch_tag_admin_update, post_tag_admin_add, post_tag_admin_module_add,
	// functions
	tag_db_init, tag_obj,
} from './methods';

import {
	Tag, TagBase, TagBaseKeys, TagBind, TagBindKeys,
	TagKeys, TagSearchResult, TagSearchResultKeys,
} from './types';

/*=== f2c_start __header ===*/

/*=== f2c_end __header ===*/

export const init = ( liwe: ILiWE ) => {
	const app = liwe.app;

	console.log( "    - tag " );

	liwe.cfg.app.languages.map( ( l ) => locale_load( "tag", l ) );
	tag_db_init ( liwe );

	app.post ( '/api/tag/admin/add', perms( [ "tag.editor" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { name, visible, ___errors } = typed_dict( req.body, [
			{ name: "name", type: "string", required: true },
			{ name: "visible", type: "boolean" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await post_tag_admin_add ( req, name, visible);
		sendResponse ( res, response );
	} );

	app.get ( '/api/tag/admin/list', perms( [ "tag.editor" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		

		const response = await get_tag_admin_list ( req, );
		sendResponse ( res, response );
	} );

	app.patch ( '/api/tag/admin/update', perms( [ "tag.editor" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { id, name, visible, ___errors } = typed_dict( req.body, [
			{ name: "id", type: "string", required: true },
			{ name: "name", type: "string" },
			{ name: "visible", type: "boolean" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await patch_tag_admin_update ( req, id, name, visible);
		sendResponse ( res, response );
	} );

	app.patch ( '/api/tag/admin/fields', perms( [ "tag.editor" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { id, data, ___errors } = typed_dict( req.body, [
			{ name: "id", type: "string", required: true },
			{ name: "data", type: "any", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await patch_tag_admin_fields ( req, id, data);
		sendResponse ( res, response );
	} );

	app.post ( '/api/tag/admin/module/add', perms( [ "tag.editor" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { id, module, ___errors } = typed_dict( req.body, [
			{ name: "id", type: "string", required: true },
			{ name: "module", type: "string", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await post_tag_admin_module_add ( req, id, module);
		sendResponse ( res, response );
	} );

	app.delete ( '/api/tag/admin/module/del', perms( [ "tag.editor" ] ),  async ( req: ILRequest, res: ILResponse ) => {
		const { id, module, ___errors } = typed_dict( req.body, [
			{ name: "id", type: "string", required: true },
			{ name: "module", type: "string", required: true }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await delete_tag_admin_module_del ( req, id, module);
		sendResponse ( res, response );
	} );

	app.get ( '/api/tag/list',  async ( req: ILRequest, res: ILResponse ) => {
		const { module, ___errors } = typed_dict( req.query as any, [
			{ name: "module", type: "string" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await get_tag_list ( req, module);
		sendResponse ( res, response );
	} );

	app.get ( '/api/tag/search',  async ( req: ILRequest, res: ILResponse ) => {
		const { tags, module, ___errors } = typed_dict( req.query as any, [
			{ name: "tags", type: "string[]", required: true },
			{ name: "module", type: "string" }
		] );

		if ( ___errors.length ) return sendParametersError ( res, ___errors );

		const response = await get_tag_search ( req, tags, module);
		sendResponse ( res, response );
	} );

};
