/* Permissions file generated by flow2code */

/*=== f2c_start __file ===*/

/*=== f2c_end __file ===*/

const permissions = {
	"tag.editor": "Only the one with this permission can change ALL the tags",
};

export default permissions;
